name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ] 

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        working-directory: ./yaman-next
        run: npm install

      - name: Run Unit Tests
        working-directory: ./yaman-next
        run: npm test

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v5
        with:
          context: ./yaman-next  
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/yaman-travels-app:latest

  deploy-to-aws:
    needs: build-and-push # Waits for build to finish
    runs-on: ubuntu-latest
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            # Go to the folder
            cd Yaman_Travels_Frontend/yaman-next
            
            # Pull the new image we just built
            docker compose pull
            
            # Restart the app (Update)
            docker compose up -d
            
            # Remove old unused images to save space (Cleanup)
            docker system prune -f
